"vundle plugin manager

syntax enable
set background=light
colorscheme elflord

set nu
set relativenumber
set hidden
set autoindent
set cindent
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
set colorcolumn=250
set laststatus=2
set cursorline
imap jj <ESC>
imap kk <ESC>
imap ww <ESC>
imap bb <ESC>
highlight ColorColumn ctermbg=lightblue guibg=lightblue

"gui options
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar
